theme: jekyll-theme-slate
title: Welcome to VasylynaYa's homepage!
description: Feel free to bookmark this to keep an eye on my project updates
<a target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=MGNhMGtycGwwbzJpNjhrdXM1cjV0ZHU0cjAgdmFzeWx5bmF5YXRza2l2MTdAbQ&amp;tmsrc=vasylynayatskiv17%40gmail.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_uk.gif"></a>
https://docs.google.com/forms/d/1ubjSg7f8XGOIv62dYcEXleKxS18fiJnwXg-0otJz7Ns/edit
