theme: jekyll-theme-slate
title: Welcome to VasylynaYa's homepage!
description: Feel free to bookmark this to keep an eye on my project updates
https://calendar.google.com/event?action=TEMPLATE&tmeid=MGNhMGtycGwwbzJpNjhrdXM1cjV0ZHU0cjAgdmFzeWx5bmF5YXRza2l2MTdAbQ&tmsrc=vasylynayatskiv17%40gmail.com
